[package]

name = "hello-world"
version = "0.0.1"
authors = ["Evan Lin <evanslin@gmail.com>"]

[dependencies.color]
git = "https://github.com/bjz/color-rs.git"

[dependencies.semver]
git = "https://github.com/rust-lang/semver.git"